//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bd1_manha.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class aluno
    {
        [Required(ErrorMessage = "Obrigatório")]
        public int num { get; set; }
        [MinLength(3, ErrorMessage = "Nome Inválido")]
        public string naluno { get; set; }
        public string codcurso { get; set; }

        [DataType(DataType.Date, ErrorMessage = "Data Inválida")]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:yyyy-MM-dd}")]
        public Nullable<System.DateTime> datanasc { get; set; }
        public Nullable<int> idade { get; set; }

        [RegularExpression(@"\d+,\d\d" , ErrorMessage ="Erro virgula")]
        public Nullable<decimal> media { get; set; }
    
        public virtual curso curso { get; set; }
    }
}
